name: manual_deploy_dev
on:
  workflow_dispatch:
    inputs:
      rama:
        description: Rama a desplegar
        required: true
        type: string

jobs:
  DevDeploy:
    runs-on: ubuntu-20.04
    steps:
      - name: "test"
        run: echo ${{github.repository}}
permissions:
  id-token: write
  contents: read
